name: LeCrone Art
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4769
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131c1b'
    - '#34546d'
    - '#965431'
    - '#dbe8de'
    - '#d09338'
  brandStrength: 0.4375
  lightness: 0.46820956584997475
  saturation: 0.09662273293361068
  rhythmicContrast: 0.6673050078097731
purpose: []
